name: Deploy Hugo site to gh-pages

on:
  push:
    branches:
      - master
      # run manually
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'  # Change this to your Hugo version
          extended: true

      - name: Build the site
        run: hugo -d support

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./support
          publish_branch: gh-pages


